/** Deployer Sub-Agent orchestration — R-DEP-2, R-DEP-4 */

import * as vscode from 'vscode';
import type { AppServices } from '../app/appServices';
import { SubAgentRunner } from '../agents/subAgentRunner';
import { evaluatePrerequisiteExit, requiresCli } from './deployPrerequisites';
import type { DeployTarget } from './deployService';
import { runBash } from '../tools/bashRunner';

export type DeployAgentIntent = 'generate' | 'apply';

export interface DeployOrchestratorResult {
  ok: boolean;
  reason?: string;
  runId?: string;
  agentAnswer?: string;
  files?: string[];
}

const AUTO_GENERATED_KEY = 'copilotPlus.deploy.autoGenerated';

export class DeployOrchestrator {
  private readonly runner: SubAgentRunner;
  private lastStatus = '';

  constructor(
    private readonly app: AppServices,
    private readonly context: vscode.ExtensionContext,
    extensionUri: vscode.Uri
  ) {
    this.runner = new SubAgentRunner(app, extensionUri);
  }

  getLastStatus(): string {
    return this.lastStatus;
  }

  async onStageEntered(from: string): Promise<void> {
    if (from !== 'Build') {
      return;
    }
    if (this.context.workspaceState.get<boolean>(AUTO_GENERATED_KEY)) {
      return;
    }
    this.lastStatus = 'Auto-generating deploy manifest (Build → Deploy)…';
    const result = await this.generateManifest();
    if (result.ok) {
      await this.context.workspaceState.update(AUTO_GENERATED_KEY, true);
      this.lastStatus = 'Deploy manifest ready.';
    } else {
      this.lastStatus = result.reason ?? 'Deploy manifest generation failed.';
    }
  }

  async generateManifest(): Promise<DeployOrchestratorResult> {
    await this.ensureBaselineManifest();

    if (this.app.platform.network.isOffline()) {
      return { ok: false, reason: 'Offline — cannot run Deployer agent.' };
    }

    const token = new vscode.CancellationTokenSource().token;
    const agent = await this.runner.runDeployer('generate', token, (msg) => {
      this.lastStatus = msg;
    });
    if (!agent.ok) {
      return { ok: false, reason: agent.reason ?? 'deployer_failed', agentAnswer: agent.finalAnswer };
    }

    const files = await this.app.deploy.listManifestFiles();
    this.lastStatus = `Manifest updated (${files.length} files).`;
    return { ok: true, agentAnswer: agent.finalAnswer, files };
  }

  async applyManifest(): Promise<DeployOrchestratorResult> {
    const cfg = this.app.deploy.getConfig();
    if (cfg.mode !== 'Auto') {
      return { ok: false, reason: 'manual_mode' };
    }

    const prereq = await this.verifyPrerequisites(cfg.target);
    if (!prereq.ok) {
      return { ok: false, reason: prereq.reason };
    }

    if (this.app.platform.network.isOffline()) {
      return { ok: false, reason: 'Offline — cannot run Deployer agent.' };
    }

    const runsBefore = this.app.deploy.getRuns().map((r) => r.id);
    const token = new vscode.CancellationTokenSource().token;
    const agent = await this.runner.runDeployer('apply', token, (msg) => {
      this.lastStatus = msg;
    });

    const completed = this.app.deploy
      .getRuns()
      .find((r) => !runsBefore.includes(r.id) && r.status === 'Completed');
    if (completed) {
      return { ok: true, runId: completed.id, agentAnswer: agent.finalAnswer };
    }

    if (!agent.ok) {
      return { ok: false, reason: agent.reason ?? 'deployer_failed', agentAnswer: agent.finalAnswer };
    }

    const direct = await this.app.deployExecutor.applyManifest();
    if (direct.ok) {
      this.lastStatus = `Deploy completed (${direct.runId}).`;
      return { ok: true, runId: direct.runId, agentAnswer: agent.finalAnswer };
    }
    return { ok: false, reason: direct.reason, agentAnswer: agent.finalAnswer };
  }

  async rollbackRun(runId: string): Promise<DeployOrchestratorResult> {
    const result = await this.app.deployExecutor.rollbackRun(runId);
    if (result.ok) {
      this.lastStatus = `Rollback completed for ${runId}.`;
      return { ok: true, runId };
    }
    return { ok: false, reason: result.reason };
  }

  private async ensureBaselineManifest(): Promise<void> {
    const files = await this.app.deploy.listManifestFiles();
    if (!files.length) {
      await this.app.deploy.generateManifest();
    }
  }

  private async verifyPrerequisites(target: DeployTarget) {
    const root = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
    if (!root) {
      return { ok: false, reason: 'no_workspace' };
    }
    const need = requiresCli(target);
    let dockerExit = 0;
    let kubectlExit = 0;
    let contextExit = 0;
    if (need === 'docker') {
      dockerExit = (await runBash('docker --version', root, 5000)).exit_code;
    }
    if (need === 'kubectl') {
      kubectlExit = (await runBash('kubectl version --client', root, 5000)).exit_code;
      contextExit = (await runBash('kubectl config current-context', root, 5000)).exit_code;
    }
    return evaluatePrerequisiteExit(target, dockerExit, kubectlExit, contextExit);
  }
}
